In [1]:

from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [ 'the glass of milk',
        ' the glass of juice',
        'the cup of tea',
        ' am a good boy',
        'I am a good developer',
        'I am rich and healthy'
]

In [3]:
sent

['the glass of milk',
 ' the glass of juice',
 'the cup of tea',
 ' am a good boy',
 'I am a good developer',
 'I am rich and healthy']

In [4]:
voc_size = 10000

In [5]:


one_hot_repr = [one_hot(words, voc_size) for words in sent]

In [6]:
one_hot_repr

[[4781, 4452, 567, 6933],
 [4781, 4452, 567, 8265],
 [4781, 6836, 567, 2861],
 [9489, 261, 530, 3680],
 [2668, 9489, 261, 530, 4042],
 [2668, 9489, 7876, 3749, 809]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8

In [10]:
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

In [11]:
print(embedded_docs)

[[   0    0    0    0 4781 4452  567 6933]
 [   0    0    0    0 4781 4452  567 8265]
 [   0    0    0    0 4781 6836  567 2861]
 [   0    0    0    0 9489  261  530 3680]
 [   0    0    0 2668 9489  261  530 4042]
 [   0    0    0 2668 9489 7876 3749  809]]


In [12]:
dim=10
model= Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')


In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 45ms/step


array([[[ 2.44057439e-02,  4.30162437e-02,  3.44367661e-02,
          2.60662921e-02, -1.31225213e-02,  8.61661509e-03,
         -4.15511355e-02, -4.59336042e-02, -4.01276238e-02,
         -1.17557757e-02],
        [ 2.44057439e-02,  4.30162437e-02,  3.44367661e-02,
          2.60662921e-02, -1.31225213e-02,  8.61661509e-03,
         -4.15511355e-02, -4.59336042e-02, -4.01276238e-02,
         -1.17557757e-02],
        [ 2.44057439e-02,  4.30162437e-02,  3.44367661e-02,
          2.60662921e-02, -1.31225213e-02,  8.61661509e-03,
         -4.15511355e-02, -4.59336042e-02, -4.01276238e-02,
         -1.17557757e-02],
        [ 2.44057439e-02,  4.30162437e-02,  3.44367661e-02,
          2.60662921e-02, -1.31225213e-02,  8.61661509e-03,
         -4.15511355e-02, -4.59336042e-02, -4.01276238e-02,
         -1.17557757e-02],
        [ 9.44608450e-03, -4.02425155e-02, -4.79964726e-02,
          3.74119394e-02,  2.20595263e-02, -4.60194610e-02,
          3.22637074e-02,  3.60790975e-02, -2.567907